package pro.perfectproduct.cramin.ingest

import org.junit.Assert.*
import org.junit.Test
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.*
import pro.perfectproduct.cramin.data.repo.DocumentFiles
import pro.perfectproduct.cramin.util.Lang
import java.util.Locale

class TextProvenanceTest {
    @get:Rule val tmp = TemporaryFolder()
    private fun sub(lang: String, auto: Boolean = false, translated: Boolean = false) = SubtitlesStream.Builder()
        .setContent("https://example.invalid/captions?lang=$lang" + if (translated) "&tlang=ru" else "", true)
        .setMediaFormat(MediaFormat.VTT).setLanguageCode(lang).setAutoGenerated(auto).build()
    private fun audio(id: String, lang: String, type: AudioTrackType?, bitrate: Int) = AudioStream.Builder()
        .setId(id).setContent("https://example.invalid/audio", true).setMediaFormat(MediaFormat.M4A)
        .setAverageBitrate(bitrate).setAudioTrackId(id).setAudioLocale(Locale.forLanguageTag(lang))
        .setAudioTrackType(type).build()

    @Test fun captionsRequireKnownMatchingLanguageAndNonAutoUntranslatedTrack() {
        val ru = sub("ru")
        assertNull(YoutubeExtractor.chooseSubtitles(listOf(ru), null))
        assertNull(YoutubeExtractor.chooseSubtitles(listOf(sub("en")), Lang.RU))
        assertNull(YoutubeExtractor.chooseSubtitles(listOf(sub("ru", auto = true)), Lang.RU))
        assertNull(YoutubeExtractor.chooseSubtitles(listOf(sub("ru", translated = true)), Lang.RU))
        assertSame(ru, YoutubeExtractor.chooseSubtitles(listOf(sub("en"), ru), Lang.RU))
    }

    @Test fun audioDoesNotPreferHigherBitrateDubOrWrongLanguage() {
        val original = audio("original", "ru", AudioTrackType.ORIGINAL, 64)
        val dub = audio("dub", "en", AudioTrackType.DUBBED, 256)
        assertSame(original, YoutubeExtractor.chooseAudio(listOf(dub, original), Lang.RU))
        assertNull(YoutubeExtractor.chooseAudio(listOf(dub), Lang.RU))
        assertNull(YoutubeExtractor.chooseAudio(listOf(original), Lang.EN))
        assertNull(YoutubeExtractor.chooseAudio(listOf(audio("a", "ru", null, 64), audio("b", "ru", null, 128)), Lang.RU))
    }

    @Test fun metadataIsBoundToExactSourceAndMissingLegacyIsUnknown() {
        val files = DocumentFiles(tmp.newFolder())
        assertEquals("UNKNOWN", files.textProvenance(1).source)
        val text = "  В simple terms Cancer RAG. в ней в ней\n\n"
        val record = TextProvenance("YOUTUBE_AUDIO_STT", "ru", "ORIGINAL", "ru", "fake/stt")
        files.writeSourceText(1, text, record)
        assertEquals(text, files.sourceText(1).readText())
        assertEquals("fake/stt", files.textProvenance(1).sttModel)
        assertFalse(files.textProvenance(1).safeSummary().contains("Cancer"))
        files.sourceText(1).writeText("different source")
        assertEquals("UNKNOWN", files.textProvenance(1).source)
        assertEquals("UNKNOWN", TextProvenance.safe("https://secret.invalid/?key=secret"))
    }
}
