package pro.perfectproduct.cramin.ingest

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.downloader.Downloader
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.exceptions.ExtractionException
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import pro.perfectproduct.cramin.data.db.DocumentEntity
import pro.perfectproduct.cramin.data.repo.DocumentFiles
import pro.perfectproduct.cramin.pipeline.ErrorCode
import pro.perfectproduct.cramin.pipeline.PipelineException
import pro.perfectproduct.cramin.util.Lang
import pro.perfectproduct.cramin.util.Log
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * YouTube (SPEC §7.2): NewPipeExtractor со своим Downloader на OkHttp. Только авторские
 * (не автоматические) субтитры на языке видео; иначе аудиопоток AAC/M4A (itag 140) во временный
 * файл для транскрипции (SPEC §8). Автосубтитры не используются ни как фолбэк, ни «временно».
 */
class YoutubeExtractor(private val http: OkHttpClient) : SourceExtractor {

    init {
        ensureInit(http)
    }

    override suspend fun extract(document: DocumentEntity, files: DocumentFiles): Extracted = withContext(Dispatchers.IO) {
        val url = document.sourceRef.trim()
        val extractor: StreamExtractor = try {
            ServiceList.YouTube.getStreamExtractor(url).also { it.fetchPage() }
        } catch (e: ReCaptchaException) {
            throw PipelineException(ErrorCode.YOUTUBE_FORMAT, "recaptcha", e)
        } catch (e: ExtractionException) {
            throw PipelineException(ErrorCode.YOUTUBE_FORMAT, e.javaClass.simpleName, e)
        } catch (e: IOException) {
            throw PipelineException(ErrorCode.NETWORK, e.javaClass.simpleName, e)
        }
        val title = runCatching { extractor.name }.getOrNull()?.trim()?.takeIf { it.isNotEmpty() }
        val subtitles = runCatching { extractor.subtitlesDefault }.getOrDefault(emptyList())
        val authored = subtitles.filter { !it.isAutoGenerated }
        // Язык видео: из метаданных; иначе — язык единственной автоматической дорожки (её содержимое
        // не используется, только факт языка речи); иначе неизвестен.
        val autoLangs = subtitles.filter { it.isAutoGenerated }.mapNotNull { langOf(it) }.distinct()
        val videoLang = runCatching { extractor.languageInfo }.getOrNull()?.let { Lang.fromCode(it.language) }
            ?: autoLangs.singleOrNull()
        Log.i(TAG, "doc=${document.id} video lang=${videoLang?.code} subtitles=${subtitles.size} authored=${authored.size} auto=${autoLangs.size}")

        val chosen = chooseSubtitles(authored, videoLang)
        if (chosen != null) {
            val subLang = langOf(chosen)
            val content = download(chosen.content)
            val format = when (chosen.format) {
                MediaFormat.VTT -> SubtitleCleaner.Format.VTT
                MediaFormat.TTML -> SubtitleCleaner.Format.TTML
                MediaFormat.SRT -> SubtitleCleaner.Format.SRT
                else -> SubtitleCleaner.detect(content, chosen.format?.suffix)
            }
            val text = SubtitleCleaner.toText(content, format)
            if (text.isBlank()) throw PipelineException(ErrorCode.EMPTY_TEXT, "subtitles empty")
            Log.i(TAG, "doc=${document.id} subtitles ${chosen.languageTag} ${format}: ${text.length} chars")
            return@withContext Extracted.Text(text = text, title = title, langHint = videoLang ?: subLang)
        }

        // Авторских субтитров нет — своя транскрипция (решение владельца, SPEC §15 п. 4).
        val audio = chooseAudio(runCatching { extractor.audioStreams }.getOrElse { throw PipelineException(ErrorCode.YOUTUBE_FORMAT, "no audio streams", it) })
            ?: throw PipelineException(ErrorCode.YOUTUBE_FORMAT, "no m4a audio stream")
        val target = File(files.audioDir(document.id), "full.m4a")
        downloadToFile(audio.content, target)
        val duration = runCatching { extractor.length.toInt() }.getOrDefault(0)
        Log.i(TAG, "doc=${document.id} audio itag=${audio.itag} bytes=${target.length()} duration=${duration}s")
        Extracted.Audio(file = target, title = title, langHint = videoLang, durationSeconds = duration)
    }

    private fun download(url: String): String = try {
        http.newCall(Request.Builder().url(url).build()).execute().use { resp ->
            if (!resp.isSuccessful) throw PipelineException(ErrorCode.YOUTUBE_FORMAT, "subtitles HTTP ${resp.code}")
            resp.body.string()
        }
    } catch (e: IOException) {
        throw PipelineException(ErrorCode.NETWORK, e.javaClass.simpleName, e)
    }

    private fun downloadToFile(url: String, target: File) {
        try {
            http.newCall(Request.Builder().url(url).build()).execute().use { resp ->
                if (!resp.isSuccessful) throw PipelineException(ErrorCode.YOUTUBE_FORMAT, "audio HTTP ${resp.code}")
                target.outputStream().use { out -> resp.body.byteStream().copyTo(out) }
            }
        } catch (e: IOException) {
            target.delete()
            throw PipelineException(ErrorCode.NETWORK, e.javaClass.simpleName, e)
        }
    }

    companion object {
        private const val TAG = "YouTube"
        const val PREFERRED_ITAG = 140

        @Volatile
        private var initialized = false

        @Synchronized
        fun ensureInit(http: OkHttpClient) {
            if (initialized) return
            NewPipe.init(OkHttpDownloader(http), Localization("en", "US"), ContentCountry("US"))
            initialized = true
        }

        fun langOf(s: SubtitlesStream): Lang? = Lang.fromCode(s.languageTag.substringBefore('-'))

        /** Авторская дорожка на языке видео; если язык неизвестен — первая авторская на поддерживаемом языке. */
        fun chooseSubtitles(authored: List<SubtitlesStream>, videoLang: Lang?): SubtitlesStream? {
            if (authored.isEmpty()) return null
            if (videoLang != null) return authored.firstOrNull { langOf(it) == videoLang }
            return authored.firstOrNull { langOf(it) != null }
        }

        /** itag 140 (AAC 128 kbps в M4A), иначе любой M4A-поток с наибольшим битрейтом. */
        fun chooseAudio(streams: List<AudioStream>): AudioStream? =
            streams.firstOrNull { it.itag == PREFERRED_ITAG }
                ?: streams.filter { it.format == MediaFormat.M4A }.maxByOrNull { it.averageBitrate }
    }
}

/** Downloader NewPipeExtractor поверх OkHttp (SPEC §5.1). */
class OkHttpDownloader(http: OkHttpClient) : Downloader() {
    private val client = http.newBuilder().readTimeout(30, TimeUnit.SECONDS).build()

    override fun execute(request: org.schabi.newpipe.extractor.downloader.Request): Response {
        val builder = Request.Builder().url(request.url())
        val body = request.dataToSend()?.toRequestBody()
        builder.method(request.httpMethod(), body)
        builder.header("User-Agent", USER_AGENT)
        for ((name, values) in request.headers()) {
            builder.removeHeader(name)
            for (v in values) builder.addHeader(name, v)
        }
        client.newCall(builder.build()).execute().use { resp ->
            if (resp.code == 429) throw ReCaptchaException("reCaptcha Challenge requested", request.url())
            val text = resp.body.string()
            return Response(resp.code, resp.message, resp.headers.toMultimap(), text, resp.request.url.toString())
        }
    }

    companion object {
        /** Тот же UA, что у клиента NewPipe: серверы YouTube отвечают на него стабильно. */
        const val USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
    }
}
