package pro.perfectproduct.cramin.live

import okhttp3.OkHttpClient
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.schabi.newpipe.extractor.ServiceList
import pro.perfectproduct.cramin.ingest.YoutubeExtractor
import pro.perfectproduct.cramin.ingest.TextProvenance
import pro.perfectproduct.cramin.util.Lang
import pro.perfectproduct.cramin.util.Log
import java.io.File
import java.util.concurrent.TimeUnit

/** Metadata-only probe: no audio download, no LLM/STT, no secret environment required. */
class YoutubeProbeTest {
    @Test
    fun probe() {
        val urls = System.getProperty("cramin.ytProbe").orEmpty().split(',').map { it.trim() }.filter { it.isNotEmpty() }
        assumeTrue("нет -PytProbe", urls.isNotEmpty())
        Log.install { _, _, _, _ -> }
        YoutubeExtractor.ensureInit(OkHttpClient.Builder().callTimeout(45, TimeUnit.SECONDS).build())
        val report = StringBuilder()
        fun record(line: String) { report.appendLine(line) }
        for (url in urls) {
            record("observedAt=${java.time.Instant.now()}")
            try {
                val ex = ServiceList.YouTube.getStreamExtractor(url).also { it.fetchPage() }
                val metadataLang = runCatching { ex.languageInfo }.getOrNull()?.language
                val subs = ex.subtitlesDefault
                val videoLang = Lang.fromCode(metadataLang) ?: subs.filter { it.isAutoGenerated }.mapNotNull { YoutubeExtractor.langOf(it) }.distinct().singleOrNull()
                record("status=FETCHED metadataLanguage=${TextProvenance.safe(metadataLang)} selectionLanguage=${videoLang?.code ?: "UNKNOWN"}")
                for ((i, s) in subs.withIndex()) record("subtitle[$i] language=${TextProvenance.safe(s.languageTag)} auto=${s.isAutoGenerated} translatedParameter=${s.content.toHttpUrlOrNull()?.queryParameter("tlang") != null} format=${s.format}")
                val audio = ex.audioStreams
                for ((i, a) in audio.withIndex()) record("audio[$i] language=${TextProvenance.safe(a.audioLocale?.toLanguageTag())} type=${a.audioTrackType ?: "UNKNOWN"} trackId=${TextProvenance.safe(a.audioTrackId)} itag=${a.itag} format=${a.format} bitrate=${a.averageBitrate}")
                val chosenSub = YoutubeExtractor.chooseSubtitles(subs, videoLang)
                val chosenAudio = if (chosenSub == null) YoutubeExtractor.chooseAudio(audio, videoLang) else null
                record("selectedSubtitle=${chosenSub?.let { subs.indexOf(it) } ?: "NONE"} selectedAudio=${chosenAudio?.let { audio.indexOf(it) } ?: "NONE"}")
            } catch (e: Exception) {
                record("status=UNAVAILABLE exception=${e.javaClass.simpleName} cause=${e.cause?.javaClass?.simpleName ?: "NONE"}")
            }
        }
        // Never export exception messages, signed URLs, titles or document/transcript text.
        val out = System.getProperty("cramin.ytProbeReport")
        if (out != null) File(out).writeText(report.toString())
        else println(report)
    }
}
