package pro.perfectproduct.cramin.live

import okhttp3.OkHttpClient
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.schabi.newpipe.extractor.ServiceList
import pro.perfectproduct.cramin.ingest.YoutubeExtractor
import pro.perfectproduct.cramin.util.Log

/** Разведка видео для живых тестов: субтитры (язык, авто?) и аудиопотоки. `-PytProbe=url1,url2`. */
class YoutubeProbeTest {
    @Test
    fun probe() {
        val urls = System.getProperty("cramin.ytProbe").orEmpty().split(',').map { it.trim() }.filter { it.isNotEmpty() }
        assumeTrue("нет -PytProbe", urls.isNotEmpty())
        Log.install { _, _, _, _ -> }
        YoutubeExtractor.ensureInit(OkHttpClient())
        for (url in urls) {
            println("=== $url")
            try {
                val ex = ServiceList.YouTube.getStreamExtractor(url).also { it.fetchPage() }
                println("  title=${ex.name} length=${ex.length}s lang=${runCatching { ex.languageInfo }.getOrNull()}")
                for (s in ex.subtitlesDefault) println("  sub: ${s.languageTag} auto=${s.isAutoGenerated} fmt=${s.format} ${s.content.take(60)}")
                for (a in ex.audioStreams) println("  audio: itag=${a.itag} fmt=${a.format} br=${a.averageBitrate} codec=${a.codec} url=${a.content.take(50)}")
            } catch (e: Exception) {
                println("  ERROR ${e.javaClass.simpleName}: ${e.message?.take(300)}")
                e.cause?.let { println("  cause ${it.javaClass.simpleName}: ${it.message?.take(300)}") }
            }
        }
    }
}
